### PR TITLE
Add RP2350 support, Arduino-Pico 4.x support

### PR DESCRIPTION
**Pull request by maxgerhardt**

### CODE REVIEW

**Comment by maxgerhardt** [comment]
Woops! This was supposed to PR into my own repo, not upstream.

**Comment by znmeb** [comment]
So is this released??

**Comment by maxgerhardt** [comment]
Released in my [platform fork](https://github.com/maxgerhardt/platform-raspberrypi/)? Yes. Released in this official repo? no.

**Comment by znmeb** [comment]
OK - got it working in my Forth project! Thanks!!

**Pull request closed without merging**
